#!/bin/bash

#install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#install packages
brew install python
pip3 install flask

brew install node
brew install git
brew install make
brew install node
brew install rbenv
brew install gcc

# Random programs
brew install neofetch
brew install youtube-dl

# Add golang install

brew cask install iterm2
brew cask install macdown
brew cask install spectacle
brew cask install transmission
brew cask install docker
brew cask install visual-studio-code
brew cask install firefox-developer-edition
brew cask install google-chrome
brew cask install telegram
brew cask install slack
brew cask install spotify
brew cask install virtualbox
brew cask install virtualbox-extension-pack
brew cask install postman
brew cask install robo-3t

# Double-check below
brew cask install drawio 
brew cask install zeplin
brew cask install iina
brew cask install boxcryptor

xcode-select --install

# Bash
echo "# Custom terminal" >> ~/.bash_profile
echo "export DEFAULT_PS1='\h:\W \u$ '" >> ~/.bash_profile
echo "export PS1='\[\033[00m\]\W \[\033[32m\]\u \[\033[1;36m\]∫ \[\033[00m\]'" >> ~/.bash_profile
echo "" >> ~/.bash_profile
echo "# Aliases" >> ~/.bash_profile
echo "alias ls='ls -G'" >> ~/.bash_profile
echo "" >> ~/.bash_profile
echo "# rbenv setup" >> ~/.bash_profile
echo "eval '\$(rbenv init -)'" >> ~/.bash_profile

# Add gitconfig controls

echo
echo Install Office Suite: https://software.tamu.edu
echo Install Sophos Home: https://home.sophos.com/en-us.aspx
echo Install OneDrive, Wunderlist, and StrongBox via the App Store
echo
echo iTerm Color Themes: https://iterm2colorschemes.com/

# Previous Brew Formulae
# ant
# autoconf
# bash-completion
# c-ares
# cmatrix
# cowsay
# fltk
# fortune
# freetype
# gcc
# gdb
# gdbm
# geckodriver
# gettext
# gflags
# git
# gmp
# grpc
# heroku
# heroku-node
# icu4c
# imagemagick
# isl
# jpeg
# kubernetes-cli
# libidn2
# libmpc
# libpng
# libtiff
# libtool
# libunistring
# lz4
# lzo
# mpfr
# neofetch
# nmap
# node
# openssl
# openvpn
# p7zip
# pandoc
# pcre
# pcre2
# pkg-config
# protobuf
# python
# python3
# python@2
# rbenv
# readline
# ruby-build
# screenfetch
# screenresolution
# sqlite
# tree
# unrar
# watchman
# wget
# xz
# youtube-dl
