#!/bin/bash

#install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#install packages
brew install python
pip3 install flask

brew install node
brew install git
brew install make
brew install node
brew install rbenv
rbenv init

brew cask install iterm2
brew cask install macdown
brew cask install spectacle
brew cask install transmission
brew cask install docker
brew cask install visual-studio-code
brew cask install firefox-developer-edition
brew cask install google-chrome
brew cask install telegram
brew cask install slack


# Add gitconfig controls

echo Install OneDrive and StrongBox via the App Store
